export const data = {
  products: [
    {
      id: '1',
      name: 'Peak Lapel Regular Blazer',
      image: '/assets/p1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      id: '2',
      name: 'Raymond Medium Fawn Blazer',
      image: '/assets/p2.jpg',
      price: 150,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '3',
      name: 'Notch Lapel Slim Blazer',
      image: '/assets/p3.jpg',
      price: 125,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: '4',
      name: 'Dark Brown Blazer',
      image: '/assets/p4.jpg',
      price: 185,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '5',
      name: 'Notch Lapel Collar Windowpane Check Blazer',
      image: '/assets/p5.jpg',
      price: 219,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '6',
      name: 'Lapel Collar Tartan Check Blazer',
      image: '/assets/p6.jpg',
      price: 105,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '7',
      name: 'SB with NO Canvas & FUSING Regular Blazer',
      image: '/assets/p7.jpg',
      price: 79,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '8',
      name: 'Arrow Men Blazer',
      image: '/assets/p8.jpg',
      price: 150,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
}
